In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [4]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

so basically here we can see that there some missing values so we are going to remove them and also removing those columns which is of no use and are duplicates

In [5]:
df = df.drop(columns=['class' , 'deck', 'alive' , 'who' , 'adult_male' , 'embark_town'])

In [6]:
df['age'] = df['age'].fillna(df['age'].median())

In [7]:
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

In [11]:
df['sex'] = df['sex'].map({'male' : 0 , 'female':1})

In [13]:
df = pd.get_dummies(df, columns=['embarked'], drop_first=True)

In [14]:
df.sample(6)

,survived,pclass,sex,age,sibsp,parch,fare,alone,embarked_Q,embarked_S
533,1,3,1,28.0,0,2,22.3583,False,False,False
138,0,3,0,16.0,0,0,9.2167,True,False,True
275,1,1,1,63.0,1,0,77.9583,False,False,True
591,1,1,1,52.0,1,0,78.2667,False,False,False
150,0,2,0,51.0,0,0,12.5250,True,False,True
424,0,3,0,18.0,1,1,20.2125,False,False,True